name: archlinux__cloudimg
env:
  base_image: "Arch-Linux-x86_64-cloudimg.qcow2"
  temp_image: "test_archlinux_cloudimg.qcow2"
  http_port: 8888
before_script:
  - curl -C - https://geo.mirror.pkgbuild.com/images/v20250701.374901/Arch-Linux-x86_64-cloudimg.qcow2 -O
  - mkdir -p http
  - printf '\n#cloud-config\nsystem_info\x3a\n  default_user\x3a\n    name\x3aroot\nchpasswd\x3a\n  list\x3a |\n    root\x3a_\n    arch\x3a_\n  expire\x3a false\nssh_deletekeys\x3a false\n' > http/user-data
  - printf 'instance-id\x3a archlinux/test\n' > http/meta-data
  - touch http/vendor-data http/network-config
  - qemu-img create -b {base_image} -f qcow2 -F qcow2 {temp_image}
http_serve:
  listen: 0.0.0.0
  access_ip: '{GATEWAY_IP}'
  port: '{http_port}'
  root: '{CWD}/http'
args:
  - # basic
    smp: '2'
    m: 4G
    smbios: type=1,serial=ds=nocloud;s=http://{GATEWAY_IP}:{http_port}/
  - drive: file={CWD}/{temp_image},if=virtio,cache=writeback,discard=ignore,format=qcow2
  - netdev: user,id=user.0,hostfwd=tcp:127.0.0.1:2022-:22
  - device: virtio-net,netdev=user.0
boot_commands:
  - wait: 1
  - read_until: "archlinux login: "
  - write: "root\r"
  - read_until: "\nPassword: "
  - write: "_\r"
  - read_until: "[root@archlinux ~]#"
  - write: [format, [quote, "stty rows %d cols %d\r\n"], TERM_ROWS, TERM_COLS]
  - write: "cloud-init status --wait\r"
  - interact: null
after_script:
  - reset -I
  - ls -l {temp_image}
  - bash -c 'read -p "delete temp image file {temp_image}(Y/n)?" choice; case "$choice" in y|Y ) echo "deleting {temp_image}"; rm {temp_image} ;; n|N ) echo "will keep {temp_image}";; * ) echo "invalid choice, do nothing";; esac'
